name: "Production Deployment"

on:
  push:
    branches:
      - release

jobs:
  build-deploy:
    name: Build and deploy application to EKS
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up GCP Service Account Key credentials
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: elliptical-feat-385302

      - name: Download gke auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Run Bash Script to Deploy
        run: |
          chmod +x deploy.sh
          bash -x deploy.sh
